# Generated by Django 6.1.1 on 2026-09-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(db_column='alert_level', max_length=10)),
                ('fraud_probability', models.DecimalField(db_column='fraud_probability', decimal_places=5, max_digits=6)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Investigation', 'Under Investigation'), ('Confirmed Fraud', 'Confirmed Fraud'), ('False Positive', 'False Positive'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_column='model_name', max_length=50)),
                ('accuracy', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('precision_score', models.DecimalField(db_column='precision_score', decimal_places=5, max_digits=6, null=True)),
                ('recall_score', models.DecimalField(db_column='recall_score', decimal_places=5, max_digits=6, null=True)),
                ('f1_score', models.DecimalField(db_column='f1_score', decimal_places=5, max_digits=6, null=True)),
                ('roc_auc', models.DecimalField(db_column='roc_auc', decimal_places=5, max_digits=6, null=True)),
                ('pr_auc', models.DecimalField(db_column='pr_auc', decimal_places=5, max_digits=6, null=True)),
                ('training_date', models.DateTimeField(db_column='training_date')),
            ],
            options={
                'db_table': 'model_metrics',
                'ordering': ['-training_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_probability', models.DecimalField(db_column='fraud_probability', decimal_places=5, max_digits=6)),
                ('risk_level', models.CharField(db_column='risk_level', max_length=10)),
                ('model_version', models.CharField(db_column='model_version', max_length=50)),
                ('latency_ms', models.DecimalField(db_column='latency_ms', decimal_places=2, max_digits=8, null=True)),
                ('prediction_time', models.DateTimeField(db_column='prediction_time')),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-prediction_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('step', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('name_orig', models.CharField(db_column='name_orig', max_length=32)),
                ('old_balance_org', models.DecimalField(db_column='old_balance_org', decimal_places=2, max_digits=18)),
                ('new_balance_orig', models.DecimalField(db_column='new_balance_orig', decimal_places=2, max_digits=18)),
                ('name_dest', models.CharField(db_column='name_dest', max_length=32)),
                ('old_balance_dest', models.DecimalField(db_column='old_balance_dest', decimal_places=2, max_digits=18)),
                ('new_balance_dest', models.DecimalField(db_column='new_balance_dest', decimal_places=2, max_digits=18)),
                ('is_fraud_actual', models.BooleanField(db_column='is_fraud_actual', null=True)),
                ('received_at', models.DateTimeField(db_column='received_at')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-received_at'],
                'managed': False,
            },
        ),
    ]
